### ISSUE TITLE
Code stealing

### ISSUE THREAD

**Issue by numerical** [aztek/porterstemmer#4]
Hey

Just wanted to let you know it seems someone has stolen your code without citing you. Just in case you care about such things. Also they've published your code under an apache 2 license rather than an MIT one.

https://github.com/JohnSnowLabs/spark-nlp/blob/master/src/main/scala/com/johnsnowlabs/nlp/annotators/Stemmer.scala

**Comment by aztek** [comment]
Thanks for telling.

I wrote this code a very long time ago for a pet project and have not really touched it since then. I only added a licence file a few months ago. It looks like the copy of the code in that repo had been made before there was a licence. Therefore, I am reluctant to do anything about the issue.
